spring:
  cache:
    type: "none"
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
    change-log: liquibase/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
logging:
  level:
    ROOT: Error
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    com.example.automaticirrigationsystem: DEBUG
tries:
  count: 2

